version: '2'
services:

  postgres:
    image: postgres:9.5.4
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reviewdb

  gerrit-master:
    image: gerrit-master
    ports:
      - "18080:8080"
      - "29418:29418"
    links:
      - postgres
    depends_on:
      - postgres

  gerrit-slave-nginx:
    image: gerrit-slave-nginx
    ports:
      - "18081:8080"
      - "29419:29418"
    links:
      - postgres
    depends_on:
      - gerrit-master

  gerrit-slave-httpd:
    image: gerrit-slave-httpd
    ports:
      - "18082:8080"
      - "29420:29418"
    links:
      - postgres
    depends_on:
      - gerrit-master
