version: '2'
services:

  postgres:
    image: postgres:9.5.4
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reviewdb
    
  master:
    build: master
    ports:
      - "18080:8080"
      - "29418:29418"
    links:
      - postgres
    depends_on:
      - postgres

  slave:
    build: slave
    ports:
      - "18888:8888"
    links:
      - postgres
    depends_on:
      - master

